export const GIFTCARDS_REQUEST = "GIFTCARDS_REQUEST";
export const GIFTCARDS_FAILURE = "GIFTCARDS_FAILURE";
export const GET_GIFTCARDS_SUCCESS = "GET_GIFTCARDS_SUCCESS";
export const POST_GIFTCARD_SUCCESS = "POST_GIFTCARD_SUCCESS";
export const FETCH_GIFTCARDS = "FETCH_GIFTCARDS";
export const DELETE_GIFTCARD = "DELETE_GIFTCARD";
