export const PACKAGES_REQUEST = "PACKAGES_REQUEST";
export const PACKAGES_FAILURE = "PACKAGES_FAILURE";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const POST_PACKAGE_SUCCESS = "POST_PACKAGE_SUCCESS";
export const FETCH_PACKAGES = "FETCH_PACKAGES";
export const DELETE_PACKAGE = "DELETE_PACKAGE";
